---

- hosts: all
  remote_user: pi
  vars:
    mosquitto_bind_address: 0.0.0.0
  roles:
    - hardening
    - homeassistant
    - base
    - openssl
    - role: trombik.mosquitto
      become: yes
      mosquitto_config:
        - "user {{ mosquitto_user }}"
        - "pid_file {{ mosquitto_pid_file }}"
        - "bind_address {{ mosquitto_bind_address }}"
        - "port {{ mosquitto_port }}"
        - "log_dest syslog"
    - role: geerlingguy.certbot
      become: yes
    - role: jdauphant.nginx
      become: yes
      nginx_configs:
        proxy:
          - map $http_upgrade $connection_upgrade {
              default upgrade;
              ''      close;
            }
          - geo $trusted {
              default 0;
              192.168.0.1/24 1;
            }
      nginx_sites:
        redirect:
          - server_name _
          - listen [::]:80 default_server ipv6only=off
          - location / {
              return 301 https://$host$request_uri;
            }
          - location /.well-known {
              alias /var/www/html/.well-known;
            }
        default:
          - server_name ha.lorenz.io
          - listen [::]:443 default_server ipv6only=off http2
          - ssl_certificate /etc/letsencrypt/live/ha.lorenz.io/fullchain.pem
          - ssl_certificate_key /etc/letsencrypt/live/ha.lorenz.io/privkey.pem
          - ssl_dhparam /etc/ssl/dhparam.pem
          - ssl_client_certificate /etc/ssl/ca.crt
          - ssl_verify_client optional
          - add_header Strict-Transport-Security "max-age=31536000; includeSubdomains"
          - ssl on
          - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
          - ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
          - ssl_prefer_server_ciphers on
          - ssl_session_cache shared:SSL:10m
          - proxy_buffering off
          - location / {
              if ($ssl_client_verify != SUCCESS) {
                set $auth_basic Restricted;
              }
              if ($ssl_client_verify = SUCCESS) {
                set $auth_basic off;
              }
              if ($trusted) {
                set $auth_basic off;
              }
              auth_basic $auth_basic;
              auth_basic_user_file htpasswd;
              proxy_pass http://localhost:8123;
              proxy_set_header Host $host;
              proxy_redirect http:// https://;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
            }
          - location /api/google_assistant {
              proxy_pass http://localhost:8123/api/google_assistant;
              proxy_set_header Host $host;
              proxy_redirect http:// https://;
              proxy_http_version 1.1;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
            }
