---

- name: Install nmap
  package: name=nmap state=installed
  become: yes

- name: Copy script
  copy: src=check_config.sh dest=/usr/local/bin mode=0755
  become: yes

- name: Copy configuration
  copy:
    src: "{{ item }}"
    dest: /home/homeassistant/.homeassistant/
    mode: 0644
    owner: homeassistant
    group: homeassistant
  become: yes
  register: ha_config
  with_items:
    - automations.yaml
    - configuration.yaml
    - customize.yaml
    - groups.yaml
    - scripts.yaml
    - secrets.yaml
    - switches.yaml
    - webostv.conf

- name: Copy known_devices
  copy:
    src: known_devices.yaml
    dest: /home/homeassistant/.homeassistant/
    mode: 0644
    owner: homeassistant
    group: homeassistant
    force: no
  become: yes

- name: Check configuration
  command: /usr/local/bin/check_config.sh
  ignore_errors: yes
  become: yes
  register: ha_check_config
  when: ha_config.changed

- debug: msg="{{ ha_check_config.stdout_lines }}"
  when: 'ha_config.changed and "Error" in ha_check_config.stdout'

- fail: msg="Configuration not valid"
  when: 'ha_config.changed and "Error" in ha_check_config.stdout'

- name: Restart homeassistant
  service: name=home-assistant@homeassistant state=restarted
  become: yes
  when: ha_config.changed

- name: copy htpasswd
  copy: src=htpasswd dest=/etc/nginx/
  become: yes

- include: gactions.yml
