- alias: Turn off lights when watching tv
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - service: scene.turn_on
      entity_id: scene.tv_playing
- alias: Turn off radio when watching tv
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  action:
    - service: switch.turn_off
      entity_id: switch.radio
- alias: Dim lights when tv is paused
  trigger:
    platform: state
    entity_id: media_player.kodi
    from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.tv_paused

- alias: Computer volume slider
  trigger:
    platform: state
    entity_id: input_number.computer_volume
  action:
    - service: mqtt.publish
      data_template:
        topic: "computer/volume/set"
        payload: '{{ states.input_number.computer_volume.state | int }}'
- alias: Computer volume changed
  trigger:
    platform: mqtt
    topic: computer/volume/status
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.computer_volume
      value: "{{ trigger.payload }}"

- alias: First person home
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - service: light.turn_on
      entity_id: light.hallway
      data:
        brightness: 255

- alias: Everyone left
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.radio
