- alias: Kodi started playing
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'playing'
  action:
    service: script.kodi_playing

- alias: Kodi was paused
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'paused'
  action:
    service: script.kodi_paused

- alias: Kodi is idle
  trigger:
    platform: state
    entity_id: media_player.kodi
    to: 'idle'
  action:
    service: script.kodi_idle

- alias: TV was turned off
  trigger:
    platform: state
    entity_id: media_player.webostv
    to: 'off'
  action:
    service: script.tv_turned_off

- alias: Computer volume slider
  trigger:
    platform: state
    entity_id: input_number.computer_volume
  action:
    service: mqtt.publish
    data_template:
      topic: "computer/volume/set"
      payload: '{{ states.input_number.computer_volume.state | int }}'

- alias: Juice radio
  trigger:
    platform: state
    entity_id: switch.juice
    to: 'on'
  action:
    service: media_player.volume_set
    data:
      entity_id: media_player.living_room_speaker
      volume_level: 0.4

- alias: Juice radio off
  trigger:
    platform: state
    entity_id: switch.juice
    to: 'off'
  action:
    service: script.google_home_volume_update

- alias: Computer volume changed
  trigger:
    platform: mqtt
    topic: computer/volume/status
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.computer_volume
      value: "{{ trigger.payload }}"

- alias: First person home
  trigger:
    platform: state
    entity_id: group.family
    to: 'home'
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: script.family_home

- alias: Everyone left
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
  action:
    service: script.family_away

- alias: Google Home volume
  trigger:
    platform: time
    minutes: 0
    seconds: 00
  condition:
    condition: state
    entity_id: switch.juice
    state: 'off'
  action:
    service: script.google_home_volume_update

- alias: Bedroom light switch single
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001644725
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.bedroom

- alias: Bedroom light switch double
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001644725
      click_type: double
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom
      brightness: 255
      transition: 1

- alias: Hallway light switch single
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b18332
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.hallway

- alias: Hallway light switch double
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b18332
      click_type: double
  action:
    service: light.turn_on
    data:
      entity_id: light.hallway
      brightness: 255
      transition: 1

- alias: Living room light switch single
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b18660
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.living_room

- alias: Living room light switch double
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b18660
      click_type: double
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: 255
      transition: 1

- alias: Kitchen light switch single
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b1855a
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.kitchen

- alias: Kitchen light switch double
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001b1855a
      click_type: double
  action:
    service: light.turn_on
    data:
      entity_id: light.kitchen
      brightness: 255
      transition: 1

- id: Blue Cube Knock
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001181437
      action_type: tap_twice
  action:
    service: light.toggle
    data:
      entity_id: light.bedroom

- id: Blue Cube Shake
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001181437
      action_type: shake_air
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom
      brightness: 255
      transition: 1

- id: Blue Cube Rotate
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d0001181437
      action_type: rotate
  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom
      transition: 0.3
      brightness: >
        {%- set delta = 40 %}
        {%if trigger.event.data.action_value | int > 0 %}
          {%- set bright = states.light.bedroom.attributes.brightness | int + delta %}
        {% else %}
          {%- set bright = states.light.bedroom.attributes.brightness | int - delta %}
        {% endif %}
        {% if bright > 255 %}
          255
        {% elif bright < 0 %}
          0
        {% else %}
          {{bright}}
        {% endif %}
