homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret time_zone
  unit_system: metric
  customize: !include customize.yaml

group: !include groups.yaml
switch: !include switches.yaml
script: !include scripts.yaml
automation: !include automations.yaml

media_player:
  - platform: kodi
    host: !secret kodi_host
  - platform: webostv
    name: webostv
    host: !secret tv_host
  - platform: cast

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - apparent_temperature_max
      - apparent_temperature_min
      - precip_intensity_max
      - uv_index

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: no
    home_interval: 5
    consider_home: 0:15

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

tts:
  - platform: google

input_number:
  computer_volume:
    name: Computer Volume
    initial: 40
    min: 0
    max: 100
    step: 10

google_assistant:
  project_id: !secret ga_project_id
  client_id: !secret ga_client_id
  access_token: !secret ga_access_token
  exposed_domains:
    - switch

xiaomi_aqara:
  gateways:
    - key: !secret xiaomi_key

light:
  - platform: lifx

mqtt:
  broker: !secret mqtt_broker

updater:
  include_used_components: True

frontend:
  javascript_version: latest

http:
sun:
