homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret time_zone
  unit_system: metric
  customize: !include customize.yaml

group: !include groups.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
media_player: !include media_players.yaml

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

light:
  - platform: lifx

frontend:
http:
config:
