homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret time_zone
  unit_system: metric
  customize: !include customize.yaml

group: !include groups.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
media_player: !include media_players.yaml
automation: !include automations.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.1/24
    track_new_devices: false
    home_interval: 5
    consider_home: 0:15

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

light:
  - platform: lifx

frontend:
http:
config:
sun:
