- platform: universal
  name: TV
  children:
    - media_player.kodi
  commands:
    turn_on:
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: Addons.ExecuteAddon
        addonid: script.json-cec
        params:
          command: activate
    turn_off:
      service: script.turn_on
      data:
        entity_id: script.tv_pause_and_turn_off
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.webostv
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.webostv
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.webostv
  attributes:
    state: sensor.tv_state
- platform: kodi
  host: !secret kodi_ip_address
- platform: webostv
  name: webostv
  host: !secret tv_ip_address
