tv_turned_off:
  sequence:
    - service: media_player.media_pause
      data:
        entity_id: media_player.kodi

kodi_paused:
  sequence:
    # only execute the following if sun below horizon
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - service: light.turn_on
      data:
        entity_id: light.bedroom
        transition: 3
        brightness_pct: 20
    - service: light.turn_on
      data:
        entity_id: light.living_room
        transition: 3
        brightness_pct: 20
    - service: light.turn_on
      data:
        entity_id: light.hallway
        transition: 3
        brightness_pct: 50
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        transition: 3
        brightness_pct: 50

kodi_playing:
  sequence:
    - service: switch.turn_off
      entity_id: switch.radio
    # only execute the following if sun below horizon
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - service: light.turn_off
      data:
        entity_id: light.bedroom
        transition: 3
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 3
    - service: light.turn_off
      data:
        entity_id: light.kitchen
        transition: 3
    - service: light.turn_on
      data:
        entity_id: light.hallway
        transition: 3
        brightness_pct: 50

kodi_idle:
  sequence:
    # only execute the following if sun below horizon
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - service: light.turn_on
      data:
        entity_id: group.lights
        transition: 5
        brightness_pct: 50


google_home_volume_update:
  sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.bedroom_speaker
        volume_level: >
          {% if now().hour < 10 %}
          0.01
          {% elif now().hour < 21 %}
          0.6
          {% elif now().hour < 23 %}
          0.4
          {% else %}
          0.01
          {% endif %}
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_speaker
        volume_level: >
          {% if now().hour < 10 %}
          0.01
          {% elif now().hour < 21 %}
          0.6
          {% elif now().hour < 23 %}
          0.4
          {% else %}
          0.01
          {% endif %}

family_home:
  sequence:
    - service: light.turn_on
      data:
        entity_id: group.lights
        transition: 3
        brightness_pct: 100

family_away:
  sequence:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.radio

computer_volume_raise:
  sequence:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.computer_volume
        value: >
          {% if (states('input_number.computer_volume') | int + 10) <= 100 %}
            {{ states.input_number.computer_volume.state | int + 10 }}
          {% endif %}

computer_volume_lower:
  sequence:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.computer_volume
        value: >
          {% if (states('input_number.computer_volume') | int - 10) >= 0 %}
            {{ states.input_number.computer_volume.state | int - 10 }}
          {% endif %}
