tv_pause_and_turn_off:
  sequence:
    - service: media_player.media_pause
      data:
        entity_id: media_player.kodi
    - service: media_player.turn_off
      data:
        entity_id: media_player.webostv
