- platform: template
  sensors:
    tv_state:
      entity_id:
        - media_player.webostv
        - media_player.kodi
      value_template: >-
        {%- if is_state('media_player.webostv', 'off') -%}
        off
        {%- else -%}
        {{ states.media_player.kodi.state }}
        {%- endif -%}
    person_samsung:
      entity_id:
        - group.person_samsung
      value_template: >-
        {%- if is_state('group.person_samsung', 'home') -%}
        Home
        {%- else -%}
        Away
        {%- endif -%}
      friendly_name: !secret samsung_name
    person_xiaomi:
      entity_id:
        - group.person_xiaomi
      value_template: >-
        {%- if is_state('group.person_xiaomi', 'home') -%}
        Home
        {%- else -%}
        Away
        {%- endif -%}
      friendly_name: !secret xiaomi_name
